base: &base
  adapter: postgresql
  timeout: 5000
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>

development:
  database: db/development.postgresql
  <<: *base

test:
  database: db/test.postgresql
  <<: *base

private:
  database: db/private.postgresql
  <<: *base

production:
  database: db/production.postgresql
  <<: *base
